Add dynamically resize watermark for large file
PrestaShop/watermark pull request #21
Opened 2020-05-18 11:35 UTC by symbwell

I have added a dynamically resized watermark with a percentage that the user can set in the options.

2020-05-18 12:13 UTC, PierreRambaud commented on watermark.php
> +class watermark extends Module
What is the reason to change the name?

2020-05-18 12:14 UTC, PierreRambaud commented on watermark.php
> +        $this->resize = isset($config['WATERMARK_RESIZE']) ? $config['WATERMARK_RESIZE'] : 50;
```suggestion
        $this->resize = isset($config['WATERMARK_RESIZE']) ? (int) $config['WATERMARK_RESIZE'] : 50;
```

2020-05-18 12:14 UTC, PierreRambaud commented on watermark.php
> +                $idImageType['WATERMARK_TYPES_' . (int)$type['id_image_type']] = true;
```suggestion
                $idImageType['WATERMARK_TYPES_' . (int) $type['id_image_type']] = true;
```
```suggestion
            if (null !== Tools::getValue('WATERMARK_TYPES_' . (int) $type['id_image_type'])) {
                $idImageType['WATERMARK_TYPES_' . (int) $type['id_image_type']] = true;
```

2020-05-18 12:15 UTC, PierreRambaud commented on watermark.php
> +            $this->_postErrors[] = $this->trans('Resize not allowed range.', [], 'Modules.Watermark.Admin');
```suggestion
            $this->_postErrors[] = $this->trans('Resize value not in the range (1 - 100).', [], 'Modules.Watermark.Admin');
```
Something like this maybe?

2020-05-18 12:15 UTC, PierreRambaud commented on watermark.php
> +            if (Tools::getValue('WATERMARK_TYPES_' . (int)$type['id_image_type'])) {
```suggestion
            if (Tools::getValue('WATERMARK_TYPES_' . (int) $type['id_image_type'])) {
```

2020-05-18 12:16 UTC, PierreRambaud commented on watermark.php
> +            $strShop = '-' . (int)$this->context->shop->id;
```suggestion
            $strShop = '-' . (int) $this->context->shop->id;
```

2020-05-18 12:16 UTC, PierreRambaud commented on watermark.php
> +        $strShop = '-' . (int)$this->context->shop->id;
```suggestion
        $strShop = '-' . (int) $this->context->shop->id;
```

2020-05-18 12:16 UTC, PierreRambaud commented on watermark.php
> +            if (!ImageManager::resize($file, $newFile, (int)$imageType['width'], (int)$imageType['height'])) {
```suggestion
            if (!ImageManager::resize($file, $newFile, (int) $imageType['width'], (int) $imageType['height'])) {
```

2020-05-18 12:16 UTC, PierreRambaud commented on watermark.php
> +            if (!ImageManager::resize($file_org, $newFileOrg, (int)$imageType['width'], (int)$imageType['height'])) {
```suggestion
            if (!ImageManager::resize($file_org, $newFileOrg, (int) $imageType['width'], (int) $imageType['height'])) {
```

2020-05-18 12:18 UTC, PierreRambaud commented on watermark.php
> +        [$imageWidth, $imageHeight] = getimagesize($imagepath);
If you do this, you must target PrestaShop 1.7.7.0, otherwise keep the list function for PHP compatibility.

2020-05-18 12:18 UTC, PierreRambaud commented on watermark.php
> +            $strShop = '-' . (int)$this->context->shop->id;
```suggestion
            $strShop = '-' . (int) $this->context->shop->id;
```

2020-05-18 12:19 UTC, PierreRambaud commented on watermark.php
> +        $lang = new Language((int)Configuration::get('PS_LANG_DEFAULT'));
```suggestion
        $lang = new Language((int) Configuration::get('PS_LANG_DEFAULT'));
```

2020-05-18 12:19 UTC, PierreRambaud commented on watermark.php
> +                $idImageTypePost['WATERMARK_TYPES_' . (int)$id] = true;
```suggestion
            if (Tools::getValue('WATERMARK_TYPES_' . (int) $id)) {
                $idImageTypePost['WATERMARK_TYPES_' . (int) $id] = true;
```

2020-05-18 12:19 UTC, PierreRambaud commented on watermark.php
> +            $idImageTypeConfig['WATERMARK_TYPES_' . (int)$conf] = true;
```suggestion
            $idImageTypeConfig['WATERMARK_TYPES_' . (int) $conf] = true;
```

2020-05-18 12:19 UTC, PierreRambaud requested changes
Nice pull request, just little comments :)

2020-05-18 12:56 UTC, symbwell commented on watermark.php
> +class watermark extends Module
It was accident. My PHPStorm made it itself when I refactoring code.

2020-05-18 12:57 UTC, symbwell commented on watermark.php
> +class watermark extends Module
Warning is "[EA] Class autoloading might be broken: file and class names are not identical.". Maybe it's unnecessary

2020-05-18 13:02 UTC, symbwell commented on watermark.php
> +        [$imageWidth, $imageHeight] = getimagesize($imagepath);
I will do it.

2020-05-18 13:44 UTC, PierreRambaud commented on composer.json
> +      "ext-gd": "*"
Nice idea :+1:

2020-05-18 13:44 UTC, PierreRambaud approved these changes

2020-05-19 07:34 UTC, symbwell commented
@PierreRambaud why the Issues tab is disabled in this repository?

2020-05-19 09:56 UTC, PierreRambaud commented
@symbwell Because all issues are managed in the main repository https://github.com/PrestaShop/PrestaShop :wink:

2020-06-22 07:33 UTC, sarahdib commented
@symbwell Could you rebase this pr ? 

Thank you :)

2020-06-22 09:27 UTC, symbwell commented
@sarahdib done :)

2020-06-24 14:45 UTC, merged

2020-06-24 14:46 UTC, Progi1984 commented
Thanks @sarahdib & @symbwell